### ISSUE TITLE
centos7 for libvirt seems broken

### ISSUE THREAD

**Issue by KaliszAd** [lavabit/robox#138] opened 2020-03-31 20:01 UTC
On the current libvirt provider generic/centos7 image I am dropped to dracut shell. "Warning: /dev/centos_centos7/root does not exist"

Other generic boxes, such as Debian10 boot without problem on the same installation.

**Comment by abbbi** [comment] 2020-04-13 20:14
Hi,

you are hitting the same issue as rhel8 in the past:

https://github.com/abbbi/robox/commit/68e5a7e7646acedaec475642f74f1ae012bbab71

have you tried setting the disk bus to

 disk_bus = "sata"

within your vagrant file? With this setting i was able to boot the generic/centos7 image, version 2.0.6 without troubles.

**Comment by abbbi** [comment] 2020-04-13 20:23
I can confirm that setting disk_bus = "virtio" fixes the boot issue, see also:

https://github.com/lavabit/robox/pull/122

**Comment by ladar** [comment] 2020-04-30 20:55
This is a pending/ongoing issue. It isn't clear what combination of packer/vagrant options will yield the best compatibility across all the different host/guest combos. Right now packer is setup to build using `virtio-scsi` and most of the Vagrantfiles are setup to use `scsi` ... but it seems that doesn't work with certain versions of libvirt. 

I don't recall the details, so I could be mistaken, but I fear that setting packer and vagrant to `virtio` will cause a different set of problems... because Red Hat uses a different definition of `virtio`. I also fear that some of the guest OSes (BSDs, etc) will also have issues with `virtio` devices. 

If anyone knows what's best, please let me know.

**Comment by ladar** [comment] 2020-04-30 21:26
Closing this issue so we can concentrate discussion on #125.

**Closed by ladar** 2020-04-30 21:26 UTC
Labels: duplicate
