### ISSUE TITLE
Debian v10 AKA buster AKA testing

### ISSUE THREAD

**Issue by mcandre** [lavabit/robox#25] opened 2018-12-25 19:57 UTC
Could we get a box for Debian Buster, which provides some newer packages for CloudABI development?

**Comment by ladar** [comment] 2018-12-26 00:18
It will definitely be added after the official release. In the past. I've added a few distros in the beta/release candidate stage, so it's likely I'll add buster when it gets to that stage... but it's hard to predict precisely when... so far my effort to include distros ahead their official release, like with, with RHEL 8, FreeBSD 12, Fedora 29, Ubuntu 18.10 have all felt like they were more effort than it was worth... so we'll see. I'm rather glad all but RHEL 8 have finally shipped. 

I think the two at the top of my wish list right now are probably Devuan 8., and HardenedBSD 12. Plus I still need to get two of my recent additions, NetBSD 8 and DragonflyBSD working on Hyper-V.

All that said, are you willing to test/work out the kinks with buster? If so, I'll create a branch with an initial buster configuration... which will essentially be a duplicate of the stretch config, with updated URLs, etc, if you're willing to test? Then merge/publish it once you work out the kinks? I'm all for sharing the fun.

**Comment by mcandre** [comment] 2018-12-27 21:49
If you publish a basic Debian buster box with at least VirtualBox provider, then I would be happy to try it out to resolve some issues I'm having with cmake + CloudABI testing :)

**Comment by ladar** [comment] 2018-12-28 14:37
What I'm saying is I can create a branch where I 'clone' my `stretch` configuration as a starting point for 'buster', with the relevant iso urls, etc updated. Using my scripted automation, I can do that quickly. What I don't have time for right now is to see if those new config will build properly using `buster`. Usually new additions require tweaks to the boot command, auto install config, or other modifications to the shell scripts (like updating a package names, etc). On the bright side, it should be systemd to systemd, so there shouldn't be too many changes, assuming the installer logic still works.

What I was saying is that if your willing to take those new configs, test them, even if it's only against Vbox/VMWare, and get it working properly, then I'll include it those boxes going forward, starting with my next roboxes build.

If not, don't worry, I'll do it eventually. I just want to get Devuan 1 and HardenedBSD 12 added first, since they're already released. And I also want to create docker images/boxes for more of the distros I already support. 

I'm also considering building more of the distros as OVAs for download https://roboxes.org ... but haven't had the time.

I'm hoping I'll get access to more build robots in January as well, which should help.

**Comment by klosnet** [comment] 2019-01-02 00:43
I have a Debian Buster working for a generic, magma, and evilpot build. I'll remember to put those in my PR soon...

**Comment by ladar** [comment] 2019-02-05 21:33
Initial, untested buster config added to the repo.

**Comment by ladar** [comment] 2019-02-05 21:33
Initial, untested buster config added to the repo.

**Closed by ladar** 2019-02-05 21:33 UTC
