### ISSUE TITLE
Debian 10 (Buster) apt issue

### ISSUE THREAD

**Issue by sangdrax8** [lavabit/robox#206] opened 2021-07-14 12:45 UTC
When using the generic/debian10 image, I am getting an error about a version change in apt.  I can fix it by allowing it to be updated and re-running apt, but I don't believe I should get this on a base debian 10 image

```
apt update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [122 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main Sources [188 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [293 kB]
Get:6 http://deb.debian.org/debian buster/main Sources [7,836 kB]
Get:7 http://security.debian.org/debian-security buster/updates/main Translation-en [152 kB]
Get:8 http://deb.debian.org/debian buster-updates/main Sources.diff/Index [7,624 B]            
Get:9 http://deb.debian.org/debian buster-updates/main amd64 Packages.diff/Index [7,624 B]
Get:10 http://deb.debian.org/debian buster-updates/main Translation-en.diff/Index [5,164 B]
Get:11 http://deb.debian.org/debian buster-updates/main Sources 2021-06-21-1401.46.pdiff [923 B]
Get:12 http://deb.debian.org/debian buster-updates/main Sources 2021-06-23-1401.37.pdiff [15.6 kB]
Get:13 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-06-21-1401.46.pdiff [656 B]
Get:14 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-06-23-1401.37.pdiff [4,999 B]
Get:12 http://deb.debian.org/debian buster-updates/main Sources 2021-06-23-1401.37.pdiff [15.6 kB]
Get:15 http://deb.debian.org/debian buster-updates/main Translation-en 2021-06-21-1401.46.pdiff [719 B]
Get:16 http://deb.debian.org/debian buster-updates/main Translation-en 2021-06-23-1401.37.pdiff [6,585 B]
Get:16 http://deb.debian.org/debian buster-updates/main Translation-en 2021-06-23-1401.37.pdiff [6,585 B]
Get:14 http://deb.debian.org/debian buster-updates/main amd64 Packages 2021-06-23-1401.37.pdiff [4,999 B]
Get:17 http://deb.debian.org/debian buster/main amd64 Packages [7,907 kB]
Get:18 http://deb.debian.org/debian buster/main Translation-en [5,968 kB]
Fetched 22.6 MB in 6s (3,776 kB/s)                                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
19 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Version' value from '10.9' to '10.10'

```

**Comment by timschumi** [comment] 2021-08-08 21:55
This looks more like a version change info message rather than an error. At least `sudo apt update && sudo apt upgrade` works just fine, even if this message appears, and the system is updated to Debian 10.10 afterwards.

In the end, messages like this are caused by the fact that you are using an old box version anyways and it's usually fixed by the time the next version of roboxes is released.

**Comment by ladar** [comment] 2021-08-19 22:19
@sangdrax8 I think @timschumi is correct. The image you were using was built against Debian 10.9.0... and the `debian10` configs have already been updated to use 10.10.0 so this message should disappear once you update the image. 

You should get a warning if the image in your local box cache is out of date, when you provision a new copy. But I don't think it will pull down and update it automatically. It's been awhile since I tested this though. 

Please reopen if your still seeing issues with the latest `3.3.6` boxes, or the forthcoming `3.4.0 release.

**Closed by ladar** 2021-08-19 22:19 UTC
